from datetime import datetime
from typing import Optional, List, Dict
from participant import Participant 

class Chat:
    def __init__(
        self,
        _id: Optional[str],
        type: str,
        participants: List[Participant],
        metadata: Optional[Dict[str, int]],
        title: Optional[str],
        created_at: datetime,
        last_message_at: Optional[datetime],
        unread_counts: Dict[str, int]
    ):
        self._id = _id
        self.type = type  # 'private' o 'group'
        self.participants = participants
        self.metadata = metadata
        self.title = title
        self.created_at = created_at
        self.last_message_at = last_message_at
        self.unread_counts = unread_counts

    @classmethod
    def create(cls, participants:list[Participant], type:str, created_at:datetime):
        return Chat(
            _id=None,  # ID will be generated by the repository
            type=type,
            participants=participants,
            metadata=None,
            title=None,
            created_at=created_at,
            last_message_at=None,
            unread_counts={participant["user_id"]: 0 for participant in participants}
        )
