from datetime import datetime
from typing import Optional, List
from attachment import Attachment  

class Message:
    def __init__(
        self,
        _id: Optional[str],
        chat_id: str,
        sender_id: str,
        sent_at: datetime,
        type: str,
        content: Optional[str],
        attachment: Optional[List[Attachment]],
        status: str
    ):
        self._id = _id
        self.chat_id = chat_id
        self.sender_id = sender_id
        self.sent_at = sent_at
        self.type = type
        self.content = content
        self.attachment = attachment or []
        self.status = status

    @classmethod
    def create(cls, sender_id: str, chat_id:str, type:str, content: Optional[str] = None, attachments: Optional[List[Attachment]] = None):
        return cls(
            _id=None,  # ID will be generated by the repository
            chat_id=chat_id,
            sender_id=sender_id,
            sent_at=datetime.now(),  # Timestamp will be set to now
            type=type,
            content=content,
            attachment=attachments or [],
            status="sent"  # Initial status
        )